### ISSUE TITLE
Brief BORG wiki documentation

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#20]
Hi Charlotte! Let's put up some minimal wiki documentation about the BORG project, so that people have another paper to read and cite. At the very least the [home page](https://github.com/drphilmarshall/Pangloss/wiki) needs updating with your project, and you might feel moved to make an additional wiki page besides.

(Linked from the #18 super-issue)

**Comment by charlottenosam** [comment]
I've added a short blurb. Will work on a wiki page - when do you want this all done by?

**Comment by drphilmarshall** [comment]
No rush - but it's nice to advertise your work! Wiki page should not take
long at all - you can start with just enough text to explain what you are
linking to on arxiv. If the code needs more explanation, there might be
need for some wiki documentation of it (and the README might need updating
of course). Thanks!

**Comment by charlottenosam** [comment]
Made a wiki page, will add more docs when I've had a chance to sort the code out.

**Comment by drphilmarshall** [comment]
Great!
