### ISSUE TITLE
Merge back in BORG code?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#21]
The base repo and @charlottenosam 's fork are about to diverge, as we get started on the weak lensing project. Ideally we would merge the code used in the BORG project back into Pangloss, so that any improvements you made relating to magnification etc will remain useable by others forking from the base. @tcollett, @charlottenosam can you comment on this, please? The minimal solution to this issue would to merge into a BORG branch, which could then accept changes from the WL project while retaining its own structure - but much better would be to submit a pull request to the base repo's master branch, so that we are all on the same page.

(Linked from the super-issue at #18)

**Comment by charlottenosam** [comment]
My fork is a mess, but the real changes were just to add magnification calculations to lightcone.py and then I butchered Reconstruct.py to spit out p(mu).

I will tidy up, then:
- [ ] I propose merging lightcone.py to include the magnification terms
- [ ] Either:
  - [ ] _Simple_ Add my "Reconstruct mu" code as a stand-alone
  - [ ] _Harder_ Incorporate p(mu) output into Reconstruct.py e.g. it could take as an input either --kappa or --mu etc?

**Comment by charlottenosam** [comment]
Code I need to tidy and plan to merge:
- [x] **pdf.py** - just allow parameter name to be mu as well as kappa
- [ ] **lightcone.py** - including mu calculations
- [ ] **config.py** - make sure everything gets named correctly
- [ ] **Drill.py** - include a paired down version to get p(mu)s
- [ ] **Combine and rename MakePDF.py and PDF_z.py**
   - MakePDF.py makes P(mu) for lines of sight based on overdensity - based on Reconstruct.py
   - PDF_z.py makes P(mu) for all lines of sight to a given redshift - for comparing P(mu) vs zs

**Comment by drphilmarshall** [comment]
Great, thanks Charlotte! I'd suggest that you name the last script
Magnifier.py, and then give it the options you need. If you can face it,
keeping the Reconstruct script as the only one that does that job, and that
takes mu or kappa options would be best (to minimze code proliferation)...

Thanks! :-)

**Comment by charlottenosam** [comment]
Done! 

I've kept Magnifier.py separate from Reconstruct to make my life easier. It contains the mechanism to match observed fields with simulated lightcones by overdensity. There are reasonable docs and I'll submit a pull request now.

**Comment by drphilmarshall** [comment]
Bravo! Thanks Charlotte :-)
