### ISSUE TITLE
Switch from atpy, pyfits to astropy

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#31]

**Comment by cdfassnacht** [comment]
From my personal code, I have lots of instances of the following, just in
case I'm using an older version of python:

try:
   from astropy.io import fits as pf
except:
   import pyfits as pf


On Wed, May 20, 2015 at 7:46 AM, Phil Marshall <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drphilmarshall/Pangloss/issues/31>.
>



-- 
Chris Fassnacht
Professor, Physics Dept.
UC Davis
1 Shields Ave.
Davis, CA 95616
+1-530-554-2600

**Comment by drphilmarshall** [comment]
OK, we are now filly switched to astropy I think - the example drilling exercise seems to work well, so I'm closing this for now.
