### ISSUE TITLE
Kappamaps should be able to plot themselves

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#33]
Add a method to the class, then demo it

**Comment by drphilmarshall** [comment]
Let's label the axes in physical coords, invert the grayscale and clean up the Demo - can you post the URL of the notebook here when you close this issue, please? Thanks @sweverett ! :-)

**Comment by sweverett** [comment]
Kappamap is now running correctly. The demo for using the class and plotting the maps is at: 

https://github.com/drphilmarshall/Pangloss/blob/wl/Demo.ipynb
