### ISSUE TITLE
Alignment of foreground galaxy/halo catalogs and convergence/shear maps

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#40]
Let's plot a piece of the foreground catalog on top of the convergence map. The clusters of galaxies had better lie on top of the kappa map density peaks! Take a look at how the `Lightcone` objects plot themselves - some of those functions might be able to be extracted into separate `def`s and re-used from the `ForegroundCatalog` class (as well as from the `Lightcone` class).

**Comment by drphilmarshall** [comment]
Hmm. I managed to break the [foreground overlay demo](https://github.com/drphilmarshall/Pangloss/blob/wl/demos/ForegroundGalaxyOverlay.ipynb), the maps no longer plot. But, the axes should be more useable now, and the importing of the pangloss module is more stable (`import pangloss` works better than `from pangloss import *`, in general).

**Comment by drphilmarshall** [comment]
PS. Despite the good work of that last commit, the following lines give a broken plot - try it out, @sweverett ... I left the demo in the state that its in because I think it's helpful for thinking about what we want the shear map overlay to do...

```
K.plot(subplot=[1.65,1.5,-1.65,-1.5])
S.plot(subplot=[1.65,1.5,-1.65,-1.5])
```

**Comment by sweverett** [comment]
All of the map overlay sub-plotting bugs seem to be fixed. The [foreground overlay demo](https://github.com/drphilmarshall/Pangloss/blob/wl/demos/ForegroundGalaxyOverlay.ipynb) shows a few examples of how it can be used as originally intended. Moving on to overlaying the catalogs now.

**Comment by drphilmarshall** [comment]
Excellent! :-)

**Comment by sweverett** [comment]
Everything finally seems to be working! Here's a nice subplot shown in the updated [foreground overlay demo](https://github.com/drphilmarshall/Pangloss/blob/wl/demos/ForegroundGalaxyOverlay.ipynb), with only some of the most massive galaxies plotted:
![total_overlay](https://cloud.githubusercontent.com/assets/8742179/8581317/d17eca8c-2574-11e5-92a6-dec19e9445ae.png)

**Comment by drphilmarshall** [comment]
Great! Looking closely at the foreground galaxy orange circles, I wonder if
they might be half a `self.PIXSCALE` off from the kappa map, what do you
think? Not a huge problem, since in the end we will use the `*map.at()`
function to interpolate from the maps to the world position of each source,
but maybe worth a quick look to see if you can find it.

**Comment by sweverett** [comment]
Do you say that because all of the convergence peaks seem a bit above the center of the orange circles? I think this might just be for this subregion. For example, I changed the subplot to a different region and got
![aligned](https://cloud.githubusercontent.com/assets/8742179/8583263/0e8697a0-2581-11e5-81c8-1bab19873628.png)
which looks aligned. I redid the image in the previous comment by shifting everything by half a `self.PIXSCALE`, and go the following:
![total_overlay2](https://cloud.githubusercontent.com/assets/8742179/8583620/dd874fd4-2583-11e5-9b3f-6eb66a502911.png)
I don't notice much of a difference either way.

**Comment by drphilmarshall** [comment]
OK, fair enough! Let's assume this is good enough for our purposes. Thanks!
