### ISSUE TITLE
Catalogs need to be able to convert physical positions to world coordinates

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#42]
This is to enable meaningful, general overlays of catalog objects on `WLMaps`.
The positions in Stefan's catalogs are in physical coordinates relative to the corresponding weak lensing maps - so we'll need to use the right map to do the catalog coordinate transformation.

For reference: each field (map) is 4 by 4 degrees, and each catalog is a 1x1 deg patch in that field. In the catalog filename GGL_los_8_7_7_3_3_N_4096_ang_4_*.txt, the field is (7,7) and the patch is (3,3). Let's choose the WCS center to be the center of field (0,0). In total we have 8x8 = 64 fields (1024 square degrees!), each containing 16 patches/catalogs.

**Comment by sweverett** [comment]
All coordinate transformations and plot overlays of galaxy catalogs and maps appear to be working correctly. However, I'm going to keep this issue open until I have access to data sets not in the (0,0) corner of the grid, as there may be bugs that don't appear until sets not in the origin grid are used.
