### ISSUE TITLE
Shearmap sampling

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#48]
There is a strange size of subplots where `Shearmap`s are not plotting correctly. When the number of pixels on an axis are ~40-200,  it looks like the bin sampling is calculated incorrectly and wrapping around to the other side of the image. We need to look back in `Shearmap` to find a better way to sample shear stick locations.

**Comment by sweverett** [comment]
Hmm, the sampling of `Shearmap` sticks doesn't appear to be the problem. I commented out the sampling and let `Shearmap` plot a stick in every bin. Even without sampling, the following image was produced:
![misaligned_1](https://cloud.githubusercontent.com/assets/8742179/8655914/12b262ca-2949-11e5-9e3a-36e6868b9815.png)
Yet when I zoomed in on a cluster, the problem disappeared:
![misaligned_2](https://cloud.githubusercontent.com/assets/8742179/8655921/271b2170-2949-11e5-8358-a59e6e9c0edf.png)
The problem is independent of how `Shearmap` interacts with the `Kappamap` figure, as the same shear stick alignment appears when only plotting the `Shearmap`. The problem isn't square vs rectangle either, as the zoomed in rectangle works while the zoomed out square does not. I'm at a loss as to what the problem is, but it always occurs when the length of the axes are around 0.1 deg.

**Comment by drphilmarshall** [comment]
It seems to be a problem only with the x coordinates, not y. Maybe quiver
is doing some thing funny? Try writing your own "stick" plotting function
(as you need for the background galaxies anyway) and using that in this
demo instead.

**Comment by sweverett** [comment]
Good idea @drphilmarshall . I'll feel more comfortable using a plotting method we fully understand anyway.

**Comment by sweverett** [comment]
Now that the background galaxies are being lensed correctly, it was easy to see that this `Shearmap` issue is only an issue with `quiver()` and does not effect any of our calculations. As this distortion only comes up quite rarely, and is purely aesthetic, we will close this issue for now to focus on more important issues. We may reopen this issue later and implement the new stick plotting method for sampled shear sticks.
