### ISSUE TITLE
Alignment of foreground galaxies and maps

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#49]
There appears to be a small alignment issue with `ForegroundCatalog`s and the `WLMap`s. This could be because the foreground galaxy positions are actually weakly lensed themselves - we (i.e. @drphilmarshall ) need to ask Stefan Hilbert whether this is the case or not.

**Comment by tcollett** [comment]
It is indeed the case.

**Comment by drphilmarshall** [comment]
I thought so! Cool that the images of galaxies are being deflected as well as distorted/magnified. Our current approach to weakly lensing a set of background galaxies is to use the gamma and kappa given in the maps, and positions distributed over those maps. I wonder if we should also be deflecting them according to the same maps, to get them to appear in the right places _relative to the observed foreground galaxies_?

**Comment by sweverett** [comment]
We decided: no deflection! So this one can be closed out.

**Comment by tcollett** [comment]
Really? That's not what Stefan said (although maybe there are different
versions)

**Comment by sweverett** [comment]
There is deflection - we've just decided not to worry about it for now.
