### ISSUE TITLE
Decide on a summary statistic for lensed galaxies and calculate it

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#51]
We need to decide whether we will first summarize the lensing of a `BackgroundCatalog` using an ellipticity correlation function or a galaxy-mass correlation function. We'll then need to decide whether we write our own method to calculate it, or use someone else's method. We also need to decide how to handle galaxies on the edge of the map.

**Comment by drphilmarshall** [comment]
I think we want both of these things! Started a conversation with the group
on Slack.

**Comment by drphilmarshall** [comment]
When using Jarvis' [TreeCorr](https://github.com/rmjarvis/TreeCorr), @beckermr reports:

> setting bin_slop = 0.05/binsize is best, where binsize = log(rmax/rmin)/Nbins

**Comment by drphilmarshall** [comment]
As I understand it we're going with shear-shear correlation functions `xiplus` and `xicross` (once @sweverett has figured out how they are related to Jarvis' complex `xip` and `xim`), and then `xit` (the galaxy-galaxy lensing NG cross-correlation between some suitably-selected set of massive foreground objects and the background shapes).

**Comment by sweverett** [comment]
Both correlation function types are coded up in their respective catalogs (shear-shear in `BackgroundCatalog`, galaxy-mass in `ForegroundCatalog`) and can be plotted using `plot_corr()` in `plotting.py`. Here are some examples:

### Shear-Shear:

![gg](https://cloud.githubusercontent.com/assets/8742179/8866992/73c38f3a-3178-11e5-9a6c-90e79fc991b2.png)

### Galaxy-Mass:

![ng](https://cloud.githubusercontent.com/assets/8742179/8866995/7e0ac86e-3178-11e5-90c9-fedde9a18524.png)
