### ISSUE TITLE
Phil needs to give Spencer the full data set

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#52]
I only have the (0,0) maps and the (0,0) foreground galaxy catalog data. Moving forward, I'll need @drphilmarshall to send me the rest of the data so I can make sure the physical to wcs transformations are working and for calculating the summary statistics over larger data sets.

**Comment by drphilmarshall** [comment]
Before, did we do this by http download from SLAC, or memory stick, in the end?

**Comment by sweverett** [comment]
I believe we put it on a USB.

**Comment by tcollett** [comment]
Does the "full dataset" include the masses on each plane? If so, please can
I have it too?

**Comment by drphilmarshall** [comment]
Hah - sadly not. We're just talking about all the galaxy catalogs for a single kappa map.

**Comment by tcollett** [comment]
No worries. Any news on getting AllZeData
