### ISSUE TITLE
Upload more reference materials

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#53]
We should upload relevant papers to the Pangloss `docs` for calculating the ellipticity and galaxy-mass correlation functions (so I know what I'm doing!). If @drphilmarshall could upload the inference resource he mentioned as well, that would be great!

**Comment by drphilmarshall** [comment]
For correlation function calculation, Jarvis et al 2004 cited from [this
repo](https://github.com/rmjarvis/TreeCorr) should be a good start.

For Bayesian inference check out [David MacKay's excellent free textbook!](http://www.inference.phy.cam.ac.uk/mackay/itprnn/book.html)

**Comment by sweverett** [comment]
Thanks @drphilmarshall !
