### ISSUE TITLE
Derive xicross from Jarvis xim and xip

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#54]
Hope this is going well, @sweverett! Looking fwd to seeing your plots in #51, once this is done and dusted.

**Comment by sweverett** [comment]
The derivation of the relationship between Schneider's and Jarvis's correlation functions is given [here](https://github.com/drphilmarshall/Pangloss/blob/wl/doc/jarvis_schneider_proof.pdf). In short:
xi_+ = `xip`
xi_- = `xim`
xi_x = 1/2(`xim_im`-`xip_im`)

**Comment by sweverett** [comment]
The xi_x is essentially zero for both the intrinsic and lensed correlation, which is to be expected.
![xi_cross1](https://cloud.githubusercontent.com/assets/8742179/8792800/381b10d8-2f21-11e5-9f2f-21b0369889cd.png)
For a magnitude reference, here is the same plot with the lensed xi_+ overlayed:
![xi_cross2](https://cloud.githubusercontent.com/assets/8742179/8792802/3c1c7e42-2f21-11e5-9737-1638bad7b736.png)
