### ISSUE TITLE
Start SULI report: correlation function notes, model check program description

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#56]
We need to start a write-up of your project, @sweverett, that will grow into your report for SULI. I suggest you take your latex doc containing the corr function derivation (which needs to be checked in if its not already) and extend it in the following ways:
- [ ] Add a brief explanation of what `\xi_{+}` and `\xi_{\times}` are, in terms of the ellipticities/shears of the  galaxies.
- [ ] Add a diagram illustrating the contributions to `\xi_{+}` and `\xi_{\times}` from pairs of galaxies (represented by sticks) in various configurations, as suggested by Pat at the last WL meeting.
- [ ] Preface all this with a brief description of the model check you are building up to carry out. I'd start with an abstract that summarizes just this part of the project, then leave the intro blank, and skip to a section called ``Checking the Halo Model'' in which you describe the test that you are going to do.

It's good to keep up to date with the write-up, so you don't have to do a lot of remembering at the end. However, in this mode you do have to be willing to refactor your latex code over time! :-)

Sound good?

**Comment by sweverett** [comment]
Good idea, but will I want to include the entire derivation in my SULI report? Maybe in an appendix?

**Comment by drphilmarshall** [comment]
Appendix sounds like a good idea - and don't forget, keep it brief - just
enough to help someone else see how it works.

**Comment by drphilmarshall** [comment]
Hey @sweverett can you check in your latex please? You can use a sensible filename like `suli-report-swe.tex' for our internal use, but the Makefile should generate a PDF file with the name required by the SULI program officer. Feel free to assign me with the Makefile editing once you have checked in!

**Comment by sweverett** [comment]
The report `suli-report-swe`has been checked in @drphilmarshall ! (just don't expect to see much yet!)

**Comment by sweverett** [comment]
This issue is no longer relevant to the state of the write-up; I'm going to close it and open more specific issues.
