### ISSUE TITLE
Ellipticity sticks and shear quivers must be plotted to scale

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#57]
This was pointed out by Chris at the WL meeting. Mandeep also made the good suggestion of adding a scale bar labelled "$\epsilon = 0.05$" (or something) so we know what we're looking at. Maybe switching to always using sticks will solve the first part automatically?

**Comment by sweverett** [comment]
The shear and ellipticity sticks now plot on the same scale (10% shear = 0.1 ellipticity) that automatically scales with the average of the two axis lengths. Each type of stick also has a scale bar in the bottom corners.
![scalebar](https://cloud.githubusercontent.com/assets/8742179/8866421/25f6a744-3171-11e5-9e02-b63402f044ea.png)
