### ISSUE TITLE
Shear in regions with strong lensing

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#58]
It looks to me as though we might not be dealing with the strong lensing regime yet, from the looks of the catalog sticks. If |g| > 1, we need to use a different lens equation - see Seitz & Schneider for the formula, but as I recall I think you just make the transformation g -> 1/g*

**Comment by sweverett** [comment]
Hmm. For strong lensing (|g|>1) Schneider gives
e^s = (1-ge_)/(e_-g_)
which rearranges to
e=(1+g(e^s)_)/(g_+(e^s)_)
When I apply the transformation g-> 1/g\* to the weak lensing equation, I haven't been able to get anything similar to this result.

**Comment by tcollett** [comment]
You can't do strong lensing with these sims - they aren't high resolution
enough and there's no baryons. Also the Born approximation breaks down, so
the whole Pangloss procedure will be broken. I think it's reasonable to
neglect any lines of sight with shear > 0.5 and forget about strong lensing
entirely

**Comment by sweverett** [comment]
Alright thanks, I'll add a check for that.

Also, is there really no way to render equations in the issues? I tried every latek and markdown combination I could think of, nothing worked.

**Comment by tcollett** [comment]
I don't think you can. Best you can do is add a hyperlink to a page that
has latex support or to a png of the equation but that's very clunky.

**Comment by drphilmarshall** [comment]
If @GitHub had supported MathJax, you could just type equations like $e=mc^2$ in latex and they would render as math, like on [math.stackexchange](http://math.stackexchange.com/editing-help) - but I guess we have to wait for this feature. @tcollett I started this issue because I saw what looked like some strongly distorted objects in @sweverett's mock background galaxy catalog visualizations - but I could be wrong. I'd also been thinking about moving beyond the Born approximation but you're right, one thing at a time! :-) Closing this.

**Comment by tcollett** [comment]
You will get strong lensing in here, it's just much rarer than it should be.

We won't get beyond Born - it's too complicated computationally, and
completely unnecessary for the weak lensing limit

Apparently github used to support mathjax but it gave them 'headaches' so
it was removed.

**Comment by drphilmarshall** [comment]
Gah!
