### ISSUE TITLE
Galaxy-Galaxy lensing: Background catalogs need to be given foreground catalogs

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#59]
The galaxy-galaxy lensing needs to be moved from `ForegroundCatalog` to `BackgroundCatalog` and be cross-correlating the foreground galaxy mass to the sheared ellipticicties of the lensed background galaxies. 

Note: Once this is completed, we can apply the 45 degree offset test to check if xi_+ goes to 0 and xi_x becomes non-zero.

**Comment by drphilmarshall** [comment]
We mustn't forget this issue: the galaxy-galaxy lensing signal should help a lot with understanding why we are currently underestimating the shear...

**Comment by sweverett** [comment]
Ok I think I got it this time. `BackgroundCatalogs` now have two options for `calculating_corr()`: The ellipticity-ellipticity (gg) correlation is an auto-correlation of the background ellipticities while the galaxy-mass (ng) correlation cross-correlates the position of the foreground galaxies with the ellipticities of the background galaxies.

Here is an example of the galaxy-galaxy correlation function for an intrinsic and lensed-by-map `BackgroundCatalog`:
![galaxy_galaxy_corr3](https://cloud.githubusercontent.com/assets/8742179/9050401/2c2b81ea-3a02-11e5-825b-e88eab23fe22.png)

**Comment by sweverett** [comment]
Very interesting result here @drphilmarshall . Calculating the ellipticity-ellipticity correlation function with ~6,000 galaxies still results in the usual under-prediction of shear power:
![cf1](https://cloud.githubusercontent.com/assets/8742179/9053631/6e839648-3a2c-11e5-815b-09865370505f.png)
However, the predicted galaxy-mass correlation function is _much_ better at predicting the observed correlation at separation distances from 0.2-1.0 arcmin.
![cf2](https://cloud.githubusercontent.com/assets/8742179/9053663/c01501ae-3a2c-11e5-9576-4ef2f80177c6.png)
 It also over-predicts the correlation on small scales and under-predicts at large scales as @drphilmarshall predicted!
