### ISSUE TITLE
Lens by Halos

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#60]
We need to be able to lens `BackgroundCatalog`'s by `ForegroundCatalog`'s as well as with `Kappamap`'s and `Shearmap`'s.

**Comment by sweverett** [comment]
`BackgroundCatalog`'s can now lens-by-map or lens-by-halos. The correlation function agreement isn't great (as expected), but here it is using just over 3,000 galaxies in the middle of the (0,0,0,0) field:
![halo_corr](https://cloud.githubusercontent.com/assets/8742179/8988977/11baeed4-369e-11e5-93b8-7d25d10d66e1.png)

**Comment by sweverett** [comment]
Here is the same plot with the cross-component of the correlation function:
![halo_corr_cross](https://cloud.githubusercontent.com/assets/8742179/8989066/b54e43d4-369e-11e5-8b94-3b016d0cd233.png)

**Comment by drphilmarshall** [comment]
Excellent! And very interesting - not what I was expecting at all :-) Now it's really time to _think_. What's your interpretation of what's going on? Why do you think the halo model predicted shear-shear correlation function (SSCF) is _lower_ than the observed one (from the shape catalog you lensed with the ray-traced density maps)? What tests might you try next?

**Comment by sweverett** [comment]
I've been puzzling over that myself. An interesting first test may be to run the color-coded correlation demo with the halo lensing to see if there's any significant difference in the scatter plots other than the amplitude of the bananas. Doing these case studies on individual lenses may hint at what's going on.

**Comment by drphilmarshall** [comment]
I guess the galaxy-galaxy lensing "ng" correlation function will tell us something similar, at higher S/N? Right now though we need some _hypotheses_ about what's happening, so that you can start making some simple changes to see which ones are part of a good explanation...

**Comment by sweverett** [comment]
Here's the latest plot with 0.5 square degrees of coverage (just a tad over 40'x40') centered at the center of the (0,0,0,0) field. It used 17,640 background galaxies (and just about maxed out my 8 GB of RAM).
![corr_17640_2](https://cloud.githubusercontent.com/assets/8742179/8994642/8e25b134-36c1-11e5-9ad6-0e60f5610040.png)

**Comment by sweverett** [comment]
Hmm. I was thinking that maybe the low power was due to a, strangely enough, _under_-estimate of the halo mass. I ran the lensing-by-halos for 0.16 square degrees centered in the (0,0,0,0) field at a lightcone radius of r=1,2, and 4 arcmin to get varying amount of mass (and thus kappa/gamma contribution).

For r = 1 arcmin:
![corr_5759_r1](https://cloud.githubusercontent.com/assets/8742179/8996578/dd09dba2-36cd-11e5-92ed-ef1f2ccbb3f9.png)
For r = 2 arcmin:
![corr_5759_r2](https://cloud.githubusercontent.com/assets/8742179/8996586/e47af506-36cd-11e5-84ea-2efb751a8932.png)
For r = 4 arcmin:
![corr_5759_r4](https://cloud.githubusercontent.com/assets/8742179/8996591/ea00c50a-36cd-11e5-94b9-b48efc557a18.png)
While increasing the radius does seem to help for a while, clearly it is not the main issue and causes the code to take much longer. I'll keep thinking of other causes.

**Comment by drphilmarshall** [comment]
How long would 8 and 16 arcmin take? You've got a nice progression going on
there.

**Comment by sweverett** [comment]
The main problem at this point is RAM. I began to run out of the 8 GBs on my machine towards the end of the last plot and it slowed down considerably. I'll try doing the same test over a smaller region and more radii.

**Comment by sweverett** [comment]
I ran the same test over 0.04 deg^2 (1,440 galaxies). I could get up to r=8 arcmin, but my machine ran out of RAM when trying r=10 arcmin and above. At that point each lightcone had ~30,000 galaxies, so not that surprising. Here are the results:

r = 1 arcmin:
![corr_1440_r1](https://cloud.githubusercontent.com/assets/8742179/8998293/296ce572-36e0-11e5-8fb5-0fe7a3456167.png)
r = 2 arcmin:
![corr_1440_r2](https://cloud.githubusercontent.com/assets/8742179/8998296/2f535f34-36e0-11e5-81b6-4e08f8ad3e16.png)
r = 4 arcmin:
![corr_1440_r4](https://cloud.githubusercontent.com/assets/8742179/8998301/3ae67912-36e0-11e5-8b6a-44091925bbf3.png)
r = 8 arcmin:
![corr_1440_r8](https://cloud.githubusercontent.com/assets/8742179/8998302/3ccd1bbe-36e0-11e5-92ee-c75cca99a748.png)
The difference between r=4 and r=8 doesn't seem to encourage any more significant convergence will be gained by increasing r, but that could be different over a larger region.

**Comment by drphilmarshall** [comment]
Looks like we might be plateau-ing...

**Comment by sweverett** [comment]
Do you think that we really need to make the lightcones this large (10,000-30,000 galaxies), or are we drawing the sample masses incorrectly? Or maybe the issue is with how we are combining the kappas/gammas? I'll try some different tests, but let me know if you think of an interesting one.

**Comment by drphilmarshall** [comment]
Tom made a good suggestion in #62, I thought. Can you suggest a good
algorithm for reducing the number of lensing events we need to calculate
per lightcone?
