### ISSUE TITLE
WL: The Need for Speed

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#62]
Hey @sweverett now that you are lensing by halos, how much CPU time does it take to predict the shear applied to one background galaxy, using the Pangloss model? Are we still a ways off being able to do a 40x40arcmin field in 1-second? What's your plan for speeding up the calculation if we are?

**Comment by sweverett** [comment]
Currently a shear prediction takes ~ 40+/-15 milliseconds, and a typical lightcone with radius of 2 arcmin has ~ 890+/-110 galaxies, so a single lensing even takes about 40-50 microseconds. This is about two orders of magnitude too slow to compute a 40x40 arcmin field in 1 second.

While we could partially solve this by distributing the lightcones across many cores, the better solution seems to be reducing the time per lensing event by either optimizing the code or writing the slow section in a compiled language like C. Looking into both of these options now.

**Comment by tcollett** [comment]
Most of these halos will have negligible contribution to the shear+kappa.
Maybe think about quick ways to discard the halos that are obviously
negligible based on distance and mass

**Comment by sweverett** [comment]
Closing this, because I'm working on various speed-ups in #72
