### ISSUE TITLE
Make and snap to grid directly after drilling

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#63]
We should imagine `BackgroundCatalog`'s to be single realizations of parameter sampling, meaning that each background object will have a decided halo mass and photometric redshift _before_ lensing. We would then account for the uncertainty in these values by realizing many `BackgroundCatalog`'s in the chosen region. This will allow us to `snapToGrid()` during the drilling process instead of during lensing.

**Comment by drphilmarshall** [comment]
Interested to see how much of a speed-up over the fiducial set-up this gives us! #62

**Comment by sweverett** [comment]
Moving the `defineSystem()`, `loadGrid()`, and `snapToGrid()` from the lensing to the drilling has decreased the CPU time per `lightcone` from 38 +/- 12 milliseconds to 28 +/- 2 milliseconds. An improvement for sure, but we're still far off from the two orders of magnitude improvement needed. Deciding how to handle #62 will likely be the determining factor for lensing speed.

**Comment by drphilmarshall** [comment]
Yesss! You're up to a factor of 3 speed up already - very encouraging :-)
