### ISSUE TITLE
Only calculate one set of kappa/gammas per lightcone

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#64]
We should add a kwarg for `lightcones` so that it can calculate and store only one set of kappa/gamma values (`add`, `keeton`, and `tom`), but have the default set to `all` so that this doesn't break old code. This will help keep the `lightcone` tables much smaller and keep its RAM usage low.

**Comment by drphilmarshall** [comment]
#62

**Comment by sweverett** [comment]
Made the changes to `lightcone` and `lens_by_map()`. Average CPU time per lightcone has dropped from 65 +/- 15 milliseconds to 38 +/- 12 milliseconds - not too bad for a quick change! This result is encouraging for the changes to be made in #67. Doing a RAM stress now.

**Comment by sweverett** [comment]
Was able to run the drilling and lensing for 9,000 galaxies without issue, and the RAM usage was noticeably lower during `lens_by_halos()`. Drilling took 50% more RAM than lensing, this should be improved after #67.
