### ISSUE TITLE
Void Correction

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#65]
We currently don't account for voids in the calculation of the convergence and shear at a point (as the mass density is definitely _not_ the average mass density of the universe at these locations). We need to think of how to account for this in `combineKappas()`, and whether this is contributing to the shear power problem we are currently facing.

**Comment by sweverett** [comment]
End of SULI status: Not much work has been done on this issue. I tried a few simple corrections for kappa, but we need to discuss how this correction would impact the shear and how to implement it.

**Comment by drphilmarshall** [comment]
[McCully et al 2016](http://arxiv.org/abs/1601.05417) make a void/smooth component correction - we might be able to just follow their lead (bearing in mind that our problem is simpler because we don't yet have a strong lens plan to focus on). What do you think?

**Comment by drphilmarshall** [comment]
While this is currently our best bet for why the halo model shear correlation function amplitude is low compared to the ray-traced one, let's not stop trying to think of other reasons for the shortfall, too...

**Comment by sweverett** [comment]
I've implemented the smooth-component correction, but there are clearly some issues. Here are the surface and volume densities for the universe (black), halos (green), and smooth-component (blue) at each redshift slice for a randomly chosen lightcone:
![volume_densities](https://cloud.githubusercontent.com/assets/8742179/14993022/7b7948b4-112e-11e6-80f1-cd3c19bd7e1c.png)
![surface_densities](https://cloud.githubusercontent.com/assets/8742179/14993023/7b79bea2-112e-11e6-8dcf-9fe288040304.png)
The halo mass density is at least an order of magnitude smaller than the universe's mean density at most redshifts, resulting in a smooth-component density that dominates over the halos. Worse, both projected surface densities are far higher than sigma_crit (plotted in red) which results in huge kappa values.

I've triple checked that I'm using the correct distance measures, volume calculations, and units, but everything seems consistent. Same order-of-magnitude results for lightcone radii varying from 1-8 arcminutes as well. The volume densities seem reasonable, so maybe I am calculating the surface densities incorrectly. (But since rho_s is constant across the redshift slice, wouldn't sigma_s simply be rho_s times the proper volume element integrated over the z range of the slice? I wrote down the details in `doc/void_correction.pdf`.)

Any ideas?

**Comment by drphilmarshall** [comment]
Hmm - your top plot indeed looks to be at odds with @sjhilbert's "50% of the mass in the universe is not in halos claim" - you're finding 90-99%... Are you including the halos as well as the subhalos ( #91 )?

With the surface mass density, isn't Sigma_s = rho_s dR, where dR is the line of sight slice thickness? I think this will be a proper line of sight distance given your other choices, right? I would guess that your slices are not more than 100's of Mpc thick, so your Sigma_s values should be about 10^11 x 10^2 ~ 10^13 Msun Mpc^{-2}, which is 100 times less than the critical density - that's good, as we expect the convergence to reach 0.01 only close to the centers of massive objects.

**Comment by sjhilbert** [comment]
More about the 50% claim: I have not checked this myself. It likely is only true if you go to the resolution limit for halos in the simulation, ie. include everything with M \geq 10^9 M_solar.

Have you looked at 
http://adsabs.harvard.edu/abs/2015MNRAS.454..708P
?

About the surface mass densities: You need to settle on a shell thickness to integrate over to get from 3D densities (e.g. the mean density) to surface mass densities. And what you get for the 2D density from the mean density should always be much smaller than the critical surface mass density (if I remember correctly, you need to integrate that at least over the whole Hubble distance to get anything near critical).

**Comment by drphilmarshall** [comment]
Thanks Stefan - I remember that paper coming out but it went past quickly,
and I was focused on their use of statistics at the time... It seems like
we could indeed be confirming their result - and that we must scour that
paper for thoughts on extending ou rmodel. Spencer, can you please read
this paper carefully and extract its relevant wisdom? Thanks!

I agree about the density orders of magnitude (and had heard the same
factoid about the mean density / critical density).

**Comment by sweverett** [comment]
Thanks for the comments everyone – it helped me find the bug! Here are are the updated, and much more reasonable, density plots:
![surface_densities4](https://cloud.githubusercontent.com/assets/8742179/15061403/9870ab92-12fa-11e6-8712-51d0bcb5505d.png)
![volume_densities4](https://cloud.githubusercontent.com/assets/8742179/15061406/a0241b3a-12fa-11e6-81a6-15b12abace2d.png)
Since such a low percentage of mass is in the halos, the correction kappas are larger than most individual halo kappa contributions except for a few that are right on the line of sight:
![kappas2](https://cloud.githubusercontent.com/assets/8742179/15061408/ab08828e-12fa-11e6-92b8-a8dff0ec5fe7.png)
The smooth-component correction led to a modest but noticeable increase in correlation across all scales for the ellipticity-ellipticity correlation function,
![gg_s_compare4](https://cloud.githubusercontent.com/assets/8742179/15061411/b8bde018-12fa-11e6-80ad-f9733c8dd2be.png)
and a smaller increase for the galaxy-mass correlation function:
![ng_s_compare4](https://cloud.githubusercontent.com/assets/8742179/15061423/cd5e4120-12fa-11e6-8929-560f3749a0f3.png)
I got similar results for a lightcone radius of 4 arcmin and when I only included ~60-80 most relevant halos. Keeping the catalogs for all three cases eats up the memory of my machine, but I did a non-comparrison run with a radius of 8 arcmin and got this result:
![ggcorr_s](https://cloud.githubusercontent.com/assets/8742179/15061440/e6d4d6c8-12fa-11e6-97d2-687bbcf48e51.png)
Looking good! Will do more testing this week, as well as speed up the correction code a bit.

**Comment by drphilmarshall** [comment]
Good! Agree this is looking promising. I'm a bit confused as to why your 2pt e-e correlation function gets so much better when you move from 6.0 arcmin lightcones (your first plot) and 8.0 arcmin lightcones. Could you check these results, and edit the comment above if there is a problem, please?

If your last plot is correct, it's nice that we now only seem to be missing shear at separations larger than 0.4 arcmin. Is this consistent with Pace et al (the paper Stefan pointed us to)? We should be able to visualize the missing mass that is causing this missing shear by subtracting the halo model kappa map from the ray-traced kappa map. If only #68 was getting some attention!

**Comment by sweverett** [comment]
I did a few more runs to check the previous results. The previous 8 arcmin plot may have been an especially good run, but we're still seeing a big improvement:
![gg_r81440_2](https://cloud.githubusercontent.com/assets/8742179/15094694/75cfdb52-1472-11e6-9ae3-b0d6b99828e4.png)
![gg_r81440_3](https://cloud.githubusercontent.com/assets/8742179/15094695/75d1e654-1472-11e6-9960-bb6ae0715980.png)
I ran another with a 6 arcmin radius and got a result that looks similar to the 8 arcmin runs:
![gg_r61440-2](https://cloud.githubusercontent.com/assets/8742179/15094701/a85788e0-1472-11e6-87d3-47870b9c6df2.png)
The correction seems to give a much higher ceiling for correlation, but possibly with more variation.

**Comment by drphilmarshall** [comment]
Good. What is the difference between these "runs"? Are they different pointings on the sky, or just different noise realizations of the background galaxies? Hopefully it's the former! When you are able to make convergence maps from the halo model ( #68 ) you should look at the correlation functions and the convergence difference map together, to diagnose where the most important missing mass is.

**Comment by sweverett** [comment]
The former! The plots I post are almost always generated through `lens_compare.py`, which generates a new background catalog each time with randomly chosen source positions within the chosen domain.

Thanks for the suggestion - should have some interesting plots soon!
