### ISSUE TITLE
Rank lensing "relevance" for all halos in a lightcone

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#66]
We need to create a metric for determining the importance of each foreground halo to the convergence/shear calculation in a given `lightcone`. As we will now have the physical distance, halo mass, and photometric redshift determined _before_ lensing, these will be very useful in determining importance. Once the importance is calculated, each `lightcone` should have an importance ranking column and then `lens_by_halo()` could use a new importance cutoff kwarg to determine how many foreground halos are used in the lensing calculation.

**Comment by drphilmarshall** [comment]
NB. the "importance" quantity must be _cheap_ to compute (#62)

**Comment by sweverett** [comment]
I've implemented a (very) basic `importance` metric for the contribution of galaxies to the lensing in a `lightcone`. However, I've been struggling to understand why there haven't been any increases to performance even when only a small subset of galaxies are used. 

After profiling the `lens_by_halos()` method, I found that roughly 1/3 of the runtime is during the `BMO1Ffunc()` and `BMO1Gfunc()` methods which are called in `makeKappas()`. This isn't surprising; what _is_ surprising is that this runtime doesn't change when the number of galaxies in the `lightcone` is decreased. Even when I force each `lightcone` to only keep one foreground galaxy, the runtime doens't noticeably change. I've double checked that only one galaxy is being passed throughout. Am I missing something obvious here?

**Comment by drphilmarshall** [comment]
Some possible obvious things:
- Is the number of halos in the lightcone really decreasing when you increase the importance threshold? You should see the correlation function power decrease and its error bars increase, as the number of foreground galaxies decreases. 
- Has the number of halos per lightcone in the calculation always just been one?!
- Is the profiler output telling you the CPU time per halo somehow?
- Is the CPU time _exactly_ the same? This would be a sign of a bug (ie that things you thought had been changed had not!)

I agree with you, that the CPU time has to scale linearly plus a constant with the mean number of halos per lightcone!

**Comment by sweverett** [comment]
- The correlation function is behaving exactly how I would expect; it approaches a noisy zero correlation in a roughly linear way as the mean number of galaxies per lightcone decreases.
- This isn't the problem due to the observation above. I've also done enough print variable checks to know that the right number of galaxies are being passed.
- The profiler output tells the CPU time per call of each method and the cumulative time spent in each method. As long as the same number of lightcones are being analyzed, these numbers are not changing in any significant way with an increase in galaxies.
- No, the CPU time isn't _exactly_ the same during any run. It's almost always within +/- 1.5 seconds out of a ~60 second runtime, but increasing the galaxy count doesn't consistently change the time in either direction.

Pretty lost as to what is going on here. I just ran another test with 1,440 lightcones at r=2 arcmin (~1,000 galaxies per lightcone) and at r=8 arcmin (~15,000 galaxies per lightcone). The cumulative runtime for most of the methods in `lensing.py` did go up by about one second. This seems encouraging, but it's hard to believe that it takes 20 s to run 1 galaxy per lightcone but only 21 s to run 15,000 per lightcone.

**Comment by drphilmarshall** [comment]
Well, the overhead associated with for loops in python is very high...Have
you tried looking at the CPU time scaling when there is just one lightcone?
(ie a backgroundcatalog with just one member! :-) )

**Comment by sweverett** [comment]
That's exactly what I'm running right now! Update soon.

**Comment by sweverett** [comment]
For 1 lightcone with r=2 arcmin (~1,000 galaxies), it took 0.46 s to run the entire `lens_by_halos()` method, with 0.31 s coming from the `F()` method in `lensing.py`. 

Ran the same test but with r=16 arcmin (~60,000 galaxies). It took 0.32 s to run the method and 0.055 s coming from the `F()` method. 

Does this make any remote sense to you?

**Comment by drphilmarshall** [comment]
:-)

**Comment by drphilmarshall** [comment]
No, but it bodes well for an all-sky survey! :-)

I wonder if there is something else going on, like your skype or browser
going crazy. Good to see if the numbers you just quoted (run times for 1
lightcone, with r = 2 and 16 arcmin) are repeatable, or if you are seeing
random scatter due to other factors.

**Comment by sweverett** [comment]
At last, some sanity has returned! I repeated the same test (1 lightcone, r=2 arcmin and r=16 arcmin) 5 times before and after I killed all other significant processes on my machine. Here are the results:

### Before:
- r = 2:      Total time = 0.20 +/- 0.01 s,        `F()` time = 0.043 +/- 0.002 s
- r = 16:    Total time = 0.33 +/- 0.01 s,        `F()` time = 0.056 +/- 0.002 s

### After:
- r = 2:      Total time = 0.188 +/- 0.002 s,        `F()` time = 0.0416 +/- 0.0008 s
- r = 16:    Total time = 0.311 +/- 0.001 s,        `F()` time = 0.0530 +/- 0.0000 s

Everything seems about right: The r=2 runtimes are consistently smaller than the r=16 times, and turning off the other processes slightly improved performance and made it less noisy. The previous result was likely a fluke.

The only cause that makes any sense at this point is that the CPU time required to construct, copy, retrieve values, etc for a single lightcone object completely dwarfs the CPU time it takes to lens even orders of magnitude more galaxies inside the lightcone. This would explain why a small increase in the # of lightcones makes such a drastic difference in runtime, while a huge increase in galaxy # per lightcone does not.

Any thoughts?

**Comment by drphilmarshall** [comment]
Very interesting - nice work. I think we might conclude from this that
software design is going to be quite important in making this inference
work! We have some very _transparent_ prototype code, but refactoring to
reduce the logistics looks like it will pay off. What are the other lensing
function times, BTW?

**Comment by drphilmarshall** [comment]
One more question: did you this test with the same `BackgroundCatalog` each
time? It'd be interesting if there was a difference in `lens_by_halos`
runtime when you call it a second time... Just checking...

**Comment by sweverett** [comment]
I was running the test with a new `BackgroundCatalog` each time. I ran the same test with the `lens_by_halo()` method called on the same catalog 5 times and there was a random spread of about 1.1 s around the mean time.

**Comment by drphilmarshall** [comment]
OK, good. How does the total run time (including drilling etc) compare
between starting a catalog and lensing by halos once, and starting a
catalog and lensing by halos N times? I'm trying to get a feel for how much
our likelihood calculation is going to cost: its roughly the lens_by_halos
time without the initial set up time.

**Comment by sweverett** [comment]
End of SULI status: All of the infrastructure needed to implement an importance metric is already in place in `background.py`, but we need to change the importance calculation to the dimensionless m/r^3 weighting that @drphilmarshall and I discussed. I'll likely have time to finish this issue once I've updated all the demos.

**Comment by sweverett** [comment]
I implemented a relevance weighting scheme of M/R^3 that was suggested by Curtis et al. in http://arxiv.org/abs/1601.05417, using a characteristic mass of `M=10^12` solar masses and characteristic distance of `R=10 kpc`. Unsurprisingly, most weights are tightly clustered around 0. Here's an example of the distribution of the mean and max weights for 1,440 lightcones with 4,800+/-100 foreground galaxies each:

![mean_max_relevance2](https://cloud.githubusercontent.com/assets/8742179/14024192/1b59aa1a-f1b6-11e5-8d80-819d6f371e38.png)

As expected, the vast majority of galaxies contribute almost no weight with just a few that have very large weights into the hundreds. From this I played around with very small relevance limits (~0.00001 to 0.001) and found that the results from my earlier report can be nearly duplicated with only a fraction of the galaxies. Here is the ellipticity-ellipticity correlation prediction of 3,239 sources using just 23+/-5 galaxies per lightcone:

![gg3239r4_23pm5](https://cloud.githubusercontent.com/assets/8742179/14024157/f5960044-f1b5-11e5-8986-b3500eef5c6b.png)

as compared to Figure 3.a of my report (http://www.slac.stanford.edu/cgi-wrap/getdoc/slac-tn-15-027.pdf), with the same number of sources but over 500 galaxies per lightcone:

![gg_corr](https://cloud.githubusercontent.com/assets/8742179/14024200/225d0168-f1b6-11e5-9ba7-dbece425b8e2.png)

Obviously both predictions are lacking, but it now seems unlikely that we will be able to recover the needed shear power just through larger lightcone sizes. We may need to focus on additional physical components of the model like issue #65.

**Comment by drphilmarshall** [comment]
Excellent! This is a great result: I was expecting to need ~100s of halos per lightcone, so this is at least a factor of 4 speed-up over my expectations. Is 23 halos per light cone consistent with McCully et al? Or do they need more because the strong lenses are more sensitive, somehow? 

Also: what's the current wall clock time per light cone (including overheads etc)? Can you add a new bar or two to the timing chart you made for your SULI report, please? Thanks!

**Comment by sweverett** [comment]
Low relevance limits converge around 18+-8 ms per lightcone. This is now mostly overhead; at least half of the time spent in `lens_by_halos()` is writing Astropy table columns while only ~5% is spent in using the look-up table.

Also worth noting: Currently `lens_by_halos()` resets the lightcone galaxy catalog to only contain those that meet the relevance limit. This is great on my end, as the memory usage by `lens_by_halos()` is offset by the freed memory from the galaxy catalog and I can experiment with larger lightcone radii before I run out of memory. However I don't think this is the result we'll want in the future; ultimately we want to keep the catalog produced by `drill_lightcones()` to remain constant, and just have `lens_by_halos()` ignore any galaxies below the relevance limit, correct?

**Comment by drphilmarshall** [comment]
Ye-es - but it's interesting that you are limited by table-writing. That
suggests that when we start doing inference (which involves repeatedly
varying parameter values and evaluating their likelihoods) we'll want to
work with tables that are as small as possible (or no tables at all, just
numpy arrays).

**Comment by drphilmarshall** [comment]
Before you close this issue, can you report on the fraction of the correlation function signals that are captured by using the N most relevant halos, please? Does N = 23 predict the N=1000 correlation function with 1% accuracy? 2%?

**Comment by sweverett** [comment]
Here are some results:

Using around 22+/-5 relevant halos per lightcone, the shear-shear and galaxy-mass correlation functions are noticeably lower than the prediction using all halos at most scales; scales lower than 1 arcsec average ~20% percent error. The normalized RMSE for each is also stated on the plots:
![gg_rel_compare_22](https://cloud.githubusercontent.com/assets/8742179/14507488/6771f61e-0188-11e6-8139-48fae83d84a7.png)
![ng_rel_compare_22](https://cloud.githubusercontent.com/assets/8742179/14507487/67700318-0188-11e6-89d6-3dc8d9b3e786.png)
The results are much better with a slightly lower relevance limit: Using 61+/-10 relevant halos per lightcone, both 'relevant' correlation functions match better on all scales and mean error falls below 10%.
![gg_rel_compare_61](https://cloud.githubusercontent.com/assets/8742179/14507543/a355f6bc-0188-11e6-96d9-100224209edb.png)
![ng_rel_compare_61](https://cloud.githubusercontent.com/assets/8742179/14507544/a35684f6-0188-11e6-83f5-0fb29684acb0.png)
Seems that 50-100 halos per lightcone might be a better benchmark if we are trying to balance speed vs accuracy.

(note: I removed any percent errors that deviated more than 5 sigma for plots or calculations since they tend to blow up near zero correlation - a region that we are not interested in)

**Comment by drphilmarshall** [comment]
Nice plots! With 60 halos per light cone, the difference between blue and
purple curves is well within the treecorr errors, so those percentage
errors may not be significant (although I'm not sure I believe the treecorr
errors). The mean absolute percentage error might be a bit sensitive to
large residuals - the median could be a better statistic to quote.
