### ISSUE TITLE
Delete unused foreground catalog columns in lightcones

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#67]
Currently, all columns in a `ForegroundCatalog`'s `galaxy` astropy table is copied to a `lightcone`'s `galaxy` table. However, most of this data is not needed for `lightcone`s and is using up valuable RAM. `drill_lightcones()` should only copy over the used data columns and then delete the `ForegroundCatalog` when finished.

**Comment by drphilmarshall** [comment]
I guess this should speed things up too, especially when working on big fields at close to the RAM limit... #62

**Comment by sweverett** [comment]
Commenting out the unused attribute `self.allgalaxies` in `lightcone` and only inputting a foreground catalog containing the 5 needed columns into `lightcone` makes a HUGE difference: 1.5 GB of RAM was used for the drilling of 9,000 galaxies instead of 4+ GB of RAM before. While this change doesn't speed up the lensing per `lightcone`, it allows us to run larger fields and test with larger `lightcone` radii.

**Comment by sweverett** [comment]
Oops! I take that back; the drilling process only took 300 MB of RAM with 9,000 galaxies!
