### ISSUE TITLE
Background galaxy catalogs should be able to bin themselves

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#68]
It could be useful for a `BackgroundCatalog` to be able to plot a map of itself with the average value of different quantities (ellipticity, shear, convergence, etc) plotted as a colormap over an inputted bin-size. This method should also be able to bin the `Kappamap`s and `Shearmap`s in the same way for direct comparison.

**Comment by drphilmarshall** [comment]
Also visualizing cosmological density fields is the thing that will make us all famous.

**Comment by sweverett** [comment]
Good point, forgot the most important part.

**Comment by sweverett** [comment]
Switched this issue to you @drphilmarshall. Have fun making mass maps!

**Comment by drphilmarshall** [comment]
Will do! :-)

**Comment by drphilmarshall** [comment]
PS. I am working on `demos/LensByHalos.nb`, so best keep off that notebook for now to avoid conflicts. Thanks!

**Comment by sweverett** [comment]
While more features could be added at a later time, background catalogs can now bin their convergence and shear values into corresponding `kappamap`s and `shearmap`s with a desired `binsize`. The lensing values binned can be from either `lens_by_maps()` or `lens_by_halos()`. Saving the figure directly to `data/binned_maps` is an option. Here are two examples, the first from `lensed=map` and the second from `lensed=halo':
Map:
![kappa_map](https://cloud.githubusercontent.com/assets/8742179/15521815/819175f4-21d3-11e6-9709-f194f21d7d7f.png)
Halo:
![kappa_halo](https://cloud.githubusercontent.com/assets/8742179/15521822/8818c45e-21d3-11e6-8828-35848abfe2c2.png)
