### ISSUE TITLE
Is lensing-by-halo working correctly?

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#69]
While trying to understand the difference in the actual vs pangloss-predicted shear power, I came across the following troubling plot:
![lens_map](https://cloud.githubusercontent.com/assets/8742179/9046938/2c933fc0-39e3-11e5-95fe-078290b52018.png)
where blue is the intrinsic ellipticity, green is the observed ellipticity, and purple is the pangloss-predicted ellipticity. I don't fully understand how the pangloss code predicts the `kappa` and `gamma` values, but the alignment of the purple sticks is bad enough to be suspect. Similar results occur for different realizations and sky domains (and I've checked that it's not an obvious units or sign error). Is it surprising that the alignment is this bad?

**Comment by drphilmarshall** [comment]
Hmm. More investigation is needed, I think! Can you make a plot showing the
halo model kappa map with its shear field overlaid, please? This is issued
elsewhere under the name of "binning" (you can first make a densely, or
regularly-sampled background catalog, then lens it by halos, and then
export binned versions of the shear and convergence as WLmaps). Alignment
etc should be easier to understand when we can see the mass.

**Comment by sweverett** [comment]
OK, I'll get to work on that!

**Comment by sweverett** [comment]
The error appears to have been a bug in `lightcone` in which the `x` position of each foreground galaxy was not correctly converted from `nRA` to `RA`. Additionally, we accounted for the declination of the galaxy when calculating its angular separation from the center of the `lightcone`. The new alignment looks much better!
![lens_map2](https://cloud.githubusercontent.com/assets/8742179/9049270/019de59c-39f5-11e5-9616-15fb99db6273.png)
