### ISSUE TITLE
Lensing function efficiency: look-up tables, memory leak

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#72]
Currently, most of the CPU time being used in `lens_by_halos()` is in the `lesning.py` methods like `BMO1Ffunc()` and `F()`. We should write a new method in `lensing.py` that also requires an inputted mask array to make the calculations for x > 1, x = 1, and x< 1 much more efficient.

**Comment by beckermr** [comment]
What is actually slow about these methods? Is it the array manipulations or the special function calls, like arctanh, etc.?

**Comment by sweverett** [comment]
We think it is all of the array searches. For example, a single `BMO1Ffunc()` call will result in 22 array searches (x[x>1], x[x!=1]), etc). There are 35 such searches in a single `makeKappas()` call.

**Comment by drphilmarshall** [comment]
To be tested, though! It might be that python does those searches very very
fast. In general there seems to be a lot of book-keeping/memory allocation
going on, which we are also trying to reduce.

**Comment by sweverett** [comment]
I switched from `cProfile` to a line-by-line profiler and analyzed `F()`. The function has has 4 method calls (`np.ones()`, `np.arccos()`, `np.arccosh()`, and `np.log()`), 7 array searches, and 10 math calls). 30.6% of the CPU time was spent on the 4 methods, while 26.4% of the CPU time was spent on searches, and 43.0% of the CPU time was spent on math calls (division, exponentiation, etc). We can't do too much to change the method or math calls, but improving how we handle the searches may make a noticeable difference.

**Comment by beckermr** [comment]
Ahh yes. I suspected the special function calls were a large-ish fraction of the computation. These can be speed up, at the cost of accuracy. See for example code here (https://code.google.com/p/fastapprox/). Given shape noise and other real-world effects, fast, approximate math calls might be OK. This sort of optimization is something to save for later however.

**Comment by sweverett** [comment]
Thanks for the link @beckermr ! @drphilmarshall and I were just talking about doing something similar, as the approximation is likely OK for the reasons you noted. I'll try out `fastapprox` when comparing my `lensing.py` methods to the originals.

**Comment by drphilmarshall** [comment]
In the end, and given that the special functions and math calls together
add up to nearly 75% of the runtime, I'm thinking we might be better off
replacing the BMO function calls with look up tables - certainly worth
experimenting with this (I don't know how fast python can do look-ups). In
any case, the searches will need reducing, so this could be the place to
start. Interested to see how it all pans out!

**Comment by drphilmarshall** [comment]
PS. I've seen `scipy.interpolate.interp1d()` used to good effect in making look-up tables in the past, see this [blog post](http://www.shocksolution.com/2008/12/a-lookup-table-for-fast-python-math/) for an example of how to do it, and a note that `scipy.interpolate.UnivariateSpline()` is "much faster". Looks pretty easy to implement!

**Comment by beckermr** [comment]
Lookup tables are indeed a good idea @drphilmarshall!

**Comment by sweverett** [comment]
Before I construct the lookup table, @drphilmarshall and I had discussed rewriting `F()` using a mask for the `x` values so that the calculation for `z` could be made in one step rather than with 3 separate searches. After many attempts, I can only get the new method CPU runtime to be comparable to the old `F()` runtime.

However, working with the methods did lead to some ideas for cleaning up `BMO1Ffunc()` and `F()` a bit! I removed some unnecessary searches in both methods and have `BMO1Ffunc()` only call `F()` once and store the value rather than calling it twice. After 5 test runs for `lens_by_halos()` before and after the changes, I found consistently that the total runtime decreased by 9.5%, the `BMO1Ffunc()` runtime decreased by 35.3%, the `F()` runtime decreased by 33.7%, and `makeKappas()` decreased by 13.5%.

Not the huge savings that we need, but at least a little improvement came out of the work! Starting the lookup tables now.

**Comment by tcollett** [comment]
2 things:

1: The searches can be avoided entirely by using functions that can take
and return complex arguments (but they are probably slower overall so it
most likely won't help)

2: One useful feature for the lookup table is that the halos are self
similar. I don't think you should need to have the mass in the table as
it's just a rescaling of distance from the centre and a multiplication.

**Comment by sweverett** [comment]
End of SULI status: The changes to `lensing.py` and `background.py` have been made to make the lensing predictions with a lookup table, but there is a memory leak that i haven't been able to debug yet. I will try to fix this during the post-SULI cleanup.

**Comment by sweverett** [comment]
Back to work! I fixed the bug in `LensingTable()` and now  `makeKappas()` can make kappa predictions using lookup tables instead of explicit calculations. There was no memory leak; just an error in the output of the table lookup functions. Using ~10,000 samples for the table, there is no significant difference between the predicted shear-shear and galaxy-galaxy correlation functions, but time savings are only around 10-20% depending on background galaxy number and lightcone radius. I will take some more data, but we may need to look for speedups elsewhere.

**Comment by sweverett** [comment]
Took some final data: With all other programs closed, I had the following results:

**Without Lookup-Table:** Mean CPU time per lightcone: 26+/-10 ms
**With Lookup-Table:** Mean CPU time per lightcone: 14+/-10 ms

Not a bad improvement! As mentioned above, the lensing table is pretty densely sampled so there is no significant difference in predicted gg or ng correlation.

**Comment by drphilmarshall** [comment]
Excellent, thanks Spencer. When you were doing the relevance analysis, how
did the with-lookup-table CPU time per lightcone vary with the number of
halos per lightcone? I'd love to see a small table or quick plot.

**Comment by sweverett** [comment]
Good idea - I'll post a plot here soon! I did a single run and with a lightcone radius of 2 arcmin (~500 galaxies) and there wasn't much of a difference. I'll try varying the radius as well.
