### ISSUE TITLE
Wiki needs to summarize summer 2015 progress

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#74]
I made a start on this: 

https://github.com/drphilmarshall/Pangloss/wiki/Inferring-the-Mass-Map-of-the-Observable-Universe-from-10-Billion-Galaxies

@sweverett can you please add the links to two suitably tidied up demos, please? If you have one on the speed-ups you could also elevate that from "Future Plans" into "Summer 2015" :-)

**Comment by drphilmarshall** [comment]
Hey Spencer! Nice job on the final report :-) I just checked it in for posterity, and linked to it from [the wiki](https://github.com/drphilmarshall/Pangloss/wiki/Inferring-the-Mass-Map-of-the-Observable-Universe-from-10-Billion-Galaxies) so that it's easy for people to find.

**Comment by sweverett** [comment]
Thanks! The wiki looks great. I'll make the demos look a bit nicer in the next few days when I have a chance. And since you linked my github profile, I'll finally add a picture!
