### ISSUE TITLE
SULI Report

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#81]
Now that an abstract and outline have been made, I will be tracking updates to the report here. The most current version of the paper can be compiled by running the `Makefile` in the `doc` directory of the `wl` branch. Feel free to make any comments or suggestions at any time! The final draft will be finished by the end of Thursday.

First draft:
- [x] Abstract
- [x] Introduction
- [x] Theory
- [x] Methods
- [x] Results
- [x] Discussion
- [x] Conclusion
- [x] Appendix

**Comment by drphilmarshall** [comment]
Looking good, @sweverett! Quick comments:
- Don't forget to include your correlation function illustration plots (as they are from your talks) in the appendix
- You need a title!
- When you have a complete draft, read it _out loud_ to yourself to catch bugs in the text
- Great to see the "progression" plot! :-) Legend needs fixing to include different radii though - and what do you mean by "these are compared to the ray-traced correlation using a radius of 2 arcminutes plotted in green" - I thought there was no radius of interest in the ray-traced version? 
- Please do report on the profiling work: your findings about the various runtimes are interesting and will help guide us when we try and optimize further.  
- Good job with the placeholder numbers: be as quantitative as you can at all times :-)

Good luck!

**Comment by sweverett** [comment]
Thanks for looking it over!
- I'm struggling with how to do this. I think the plots are very helpful (and nice original work), but I found out there's a maximum word count that I'm already right on the limit of. There's also a limit to the number of appendix pages you can have and I definitely can't fit both explanations of the plots _and_ the correlation function derivation. Do you think the plots are a definite must-have? If so I'll work something out.
- Working on it!
- Will do.
- I'm pretty sure I updated the figure to have the radius in the legend titles - maybe I hadn't committed it yet or you had an old version. Also, you're completely right! There entire foreground catalog is used for the ray-traced correlation plot every time. I'll change that.
- I haven't made the plot yet, but some of the profiling work is included in the newest version (but I'm running into word count issues).
- Most of the numbers have now been filled!

The report needs to be turned in by the end of the work day tomorrow. If I have to remove sections like the profiling to fit DOE requirements, I can always add them back in for what I give to you.

**Comment by sweverett** [comment]
Also - ignore figure placement for now. Not being picky until all the text is finished!

**Comment by drphilmarshall** [comment]
I think you can shorten the derivations somewhat, to make room for the
figures in the appendix. Also, when you read through the text, you might be
able to tighten up the wording quite a bit: the introduction can be quite a
bit shorter, and the discussion you can make more concise too I think. You
can be more terse because your primary audience is other scientists - the
DoE readers will expect this. Certainly I'd say you should compromise on
wordiness before you compromise on content!

Lastly, if it's just a page limit in the appendix (and not a word limit),
you can reduce the font to \footnotesize in that section. But try and
compress the text first, out of sympathy for your reader! :-)

**Comment by sweverett** [comment]
The report is turned in! Thanks for all your help @drphilmarshall!
