### ISSUE TITLE
SULI report: figures need checking in

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#83]
I get compile errors without it!

**Comment by sweverett** [comment]
Oops! Thought I had added that one. Does it work now?

**Comment by drphilmarshall** [comment]
Yes and no: now you need to check in `figs-swe/xip_colormap.png` and `figs-swe/xix_colormap.png` :-)

**Comment by sweverett** [comment]
Done! I think that's all of them - I'll try to keep up better on my end.

**Comment by drphilmarshall** [comment]
Great - compilation success. Its looking very good now - very nice job. Will catch up with you again tomorrow - good luck finishing it off!
