### ISSUE TITLE
How long does a likelihood calculation take?

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#93]
While we are not quite ready to start on inference, it would be useful to report an estimate for the time it takes to make a single likelihood calculation (with and without drilling) for my thesis presentation to discuss its future feasibility. Without worrying too much about the result yet, I can implement the likelihood measure given on page 61 of @drphilmarshall 's [thesis](http://www.slac.stanford.edu/~pjm/Site/CV_files/Marshall_PhDthesis.pdf) and infer the halo masses from an assumed stellar mass - halo mass relation, and then time how long it takes.

**Comment by drphilmarshall** [comment]
Actually it would be instructive to know the value of the chi-squared that
is one of the terms of the log likelihood: if you use the same intrinisc
ellipticity distribution width in the chi-sq calculation as in the
generation of the mock data, you can use the chi-sq to quantify how bad the
model is. The number of degrees of freedom, Ndof, is the number of data
points (2 x the number of background galaxies) minus the number of
parameters (the total number of relevant halos, each with an unknown mass);
normally one would look at the reduced chi-sq (= chi-sq/Ndof), or the
chi-sq distribution for Ndof degrees of freedom, but usually Ndof is not
negative. How does the number of relevant halos compare with the number of
data points?

**Comment by drphilmarshall** [comment]
Closed by Spencer's thesis!
