### ISSUE TITLE
Kappamaps have stopped plotting!

### ISSUE THREAD

**Issue by sweverett** [drphilmarshall/Pangloss#95]
While a lot of progress has been made on #68 - the `kappamaps` have stopped plotting! This is odd as no change was made to the `plot()` method of `kappamap` or `wlmap`, and `shearmaps` still plot correctly. Hard to make binned `kappamaps` if the Hilbert maps won't plot!

**Comment by drphilmarshall** [comment]
Sounds like some sort of stupid matplotlib error, or perhaps a rogue map rescaling/offset. Should be straightforward to diagnose and fix!

**Comment by sweverett** [comment]
`kappamaps` and `shearmaps` are plotting correctly once again! While switching to `astropy` plots and transformations fixed most of the issues, there was also a deeply hidden bug in `read_in_fits_data()` that has been with us the whole time which caused problems in specific plotting scenarios. Everything seems back to normal!

**Comment by drphilmarshall** [comment]
Excellent! Well spotted. Onwards to the mass map differencing!
