### ISSUE TITLE
Visualize missing mass

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#96]
I'd suggest a three panel plot: ray traced kappa, halo model-predicted kappa, difference, to illustrate the quantitative findings coming from #94 - what do you think?

**Comment by sweverett** [comment]
This can now be done with the `compare_binned_maps()` method in `plotting.py`, given two binned `kappamaps` that result from running `bin_to_map()` using lens-by-map and lens-by-halo ellipticities.

Here's an example:
![kappamaps2](https://cloud.githubusercontent.com/assets/8742179/15521521/e383a130-21d1-11e6-9096-274c52003bdc.png)
where the left is a binned Hilbert map, the center is the predicted binned `kappamap`, and the right is the difference of the two maps. All images use the same intensity mapping. Analysis of results is in issue #94 .
